### ISSUE TITLE
Implement data acquisition

### ISSUE THREAD

**Issue by amis92** [BSData/phalanx#25]
Enable browsing BSData Gallery and downloading files from there.

For MVP here, we're aiming at:

- [x] downloading the Gallery JSON index: `bsdata.catpkg-gallery.json` form https://github.com/BSData/gallery/releases/tag/index-v1
- [ ] showing a game system (repository) selection UI for a new roster - keep ability to select Sample Dataset
- [ ] try to match the gamesystem ID with Gallery JSON's item (repository) when opening a roster.

[BSData Gallery](https://github.com/BSData/gallery) is a nuget.org/npm.org like Registry/Gallery that indexes gamesystems. It provides a static index asset.

Datafiles are available from GitHub data repositories via GitHub release assets. Sadly, those assets do not have CORS headers set, so that downloading them in a browser won't work.

Solutions I can see:
1. Make Gallery "cache" the actual assets in a branch published to GitHub Pages. Content published there is CORS-enabled and can be freely downloaded in a browser.
2. Create and use our own CORS-proxy. One thing I've researched is a Cloudflare-cors-proxy, using Cloudflare Workers.
  - an example is available here: https://github.com/Darkseal/CORSflare
  - another is a specialized one for GitHub Assets: https://github.com/kdrag0n/github-releases-proxy

**Comment by drobertson35** [comment]
Needed functionality:
- browse list of game systems and repositories (CORS issue)
- download data files (CORS issue)
- store/manage metadata in local storage
- (adv. feature) allow users to sync data across devices

**Comment by nstephenh** [comment]
I believe we can use the same proxy that godmode uses: https://cors.isomorphic-git.org/github.com/Bsdata/horus-heresy/info/refs?service=git-upload-pack

**Comment by amis92** [comment]
Cloudflare proxy is setup at `https://phalanx-cors.bsdata.workers.dev`

To get a GitHub URL with CORS headers, pass the full GH URL in a search parameter: `https://phalanx-cors.bsdata.workers.dev/?https://github.com/thing/you/want`
